name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Buildozer Action
        uses: kivy/buildozer-action@v1
        with:
          save_buildozer_cache: true
          buildozer_version: stable
